[program:t8]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/t8.sh
autostart=false
autorestart=unexpected
startsecs=1
startretries=3
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
